### ISSUE TITLE
Investigating Optical Transmission Error Correction using Wavelet Transforms

### ISSUE THREAD

**Issue by Weam84** [UHBiocomputation/UH-biocomputation-web#29]
@conference{esann2017,
author={Binjumah, Weam M and Redyuk, Alexey and Adams, Rod and Davey, Neil and Sun, Yi},
title = {Investigating Optical Transmission Error Correction using Wavelet Transforms},
booktitle = {ESANN 2017 proceedings, 25th European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning - (Bruges (Belgium), 26-28 April 2017)},
year = {2017},
pages={447-452},
publisher={ESANN}},
isbn={978-287587039-1}
 address = {Bruges, Belgium},
}
Url= https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2017-45.pdf
Url (proceeding) = https://www.i6doc.com/nl/book/?GCOI=28001100477480

**Comment by sanjayankur31** [comment]
Hey @Weam84 - is this complete? The entry doesn't have the name of the journal etc in it?

**Comment by Weam84** [comment]
Ok , I'll check it again now

**Comment by Weam84** [comment]
@conference{esann2017,
author={Binjumah, Weam M and Redyuk, Alexey and Adams, Rod and Davey, Neil and Sun, Yi},
title = {Investigating Optical Transmission Error Correction using Wavelet Transforms},
booktitle = {ESANN 2017 proceedings, 25th European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning - (Bruges (Belgium), 26-28 April 2017)},
year = {2017},
pages={447-452},
publisher={ESANN}},
isbn={978-287587039-1}
 address = {Bruges, Belgium},
}

Url = {https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2017-45.pdf}

**Comment by Weam84** [comment]
Hi Ankur,

I've just updated it
