### ISSUE TITLE
New publication Christoph

### ISSUE THREAD

**Issue by ChristophMetzner** [UHBiocomputation/UH-biocomputation-web#30]
@article{metzner2017modules,
  title={Modules for Automated Validation and Comparison of Models of Neurophysiological and Neurocognitive Biomarkers of Psychiatric Disorders: ASSRUnit - A Case Study},
  author={Metzner, Christoph and M{\"a}ki-Marttunen, Tuomo and Zurowski, Bartosz and Steuber, Volker},
  journal={arXiv preprint arXiv:1712.06353},
  year={2017}
}

**Comment by sanjayankur31** [comment]
Dunzo - site regenerated too.
