### ISSUE TITLE
Travis fails to install environement from requirements file

### ISSUE THREAD

**Issue by edd26** [UHBiocomputation/UH-biocomputation-web#50]
Travis fails to install environement from "requirements.txt" file.

My random guess for reason is the outdated Python (3.4 version).

**Comment by sanjayankur31** [comment]
#49 "fixes" it since we move from Travis to GitHub actions where it works fine with Py3.9. Travis.org is shutting down, so it's sort of time to move away from it already. For example see:

https://github.com/NeuralEnsemble/libNeuroML/issues/97

**Comment by edd26** [comment]
Ok, thanks for fixing it. I am sorry I have not looked into that in details.

Since we will not be using travis anymore, I removed "build-failing" status badge from the README file and replaced it with test build status.
